### ISSUE TITLE
Support python 3 or not?

### ISSUE THREAD

**Issue by xinmingzhang** [falgore88/command_manager#1]
hi, the command_manager seemed quite interesting, but does it only support python 2? I tried to install it under python 3.4, the error shows

F:\>pip install command_manager
Collecting command_manager
  Using cached command_manager-1.0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\TJ\AppData\Local\Temp\pip-build-dvgquw6p\command-manager\setup.py", line 32
        print filepaths
                      ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\TJ\AppData\Local\Temp\pip-build-dvgquw6p\command-manager\

I do know whether is it hard to let it support python 3 ：）

**Comment by falgore88** [comment]
add support python 3
